### ISSUE TITLE
2.3.1 release

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#416]
**Ready** when all other issues forming part of the release are **Done**.

- [x] merge dev/release-x.y.z to master
- [x] tag master
- [x] smoke test package
- [x] await release of https://github.com/xunit/xunit/issues/1611
- [x] take a dep on xunit.analyzers 0.9.0 - #440
- [x] re-tag master
- [x] re-smoke test package
- [x] convert tag to GH release
- [x] push package
- [x] tweet, mentioning contributors
- [x] post tweet in [Gitter](https://gitter.im/xbehave/xbehave.net)
- [x] increment patch version on dev
- [x] create next milestone
- [x] update samples/raise issue - https://github.com/xbehave/xbehave.net-samples/issues/21
- [x] close this milestone
- [ ] ~raise PR's to consumers:~
  - [ ] ~3rd party:~
    - [ ] ~https://github.com/agartee/Brickweave~
    - [ ] ~https://github.com/config-r/config-r~
    - [ ] ~https://github.com/DSilence/MiniPie~
    - [ ] ~https://github.com/KallynGowdy/ReactiveUI.Routing~
    - [ ] ~https://github.com/scriptcs/scriptcs~
  - [ ] ~other:~
    - [ ] ~https://github.com/adamralph/liteguard~
    - [ ] ~https://github.com/adamralph/simple-exec~
    - [ ] ~https://github.com/FakeItEasy/FakeItEasy~
    - [ ] ~https://github.com/xbehave/xbehave.net-samples~

**Comment by adamralph** [comment]
On hold, because the removal of `Fact` from the inheritance tree of `Background` is triggering xunit1013. [Conversation on Slack](https://xunit.slack.com/archives/C034MFNED/p1515005182000540).

**Comment by adamralph** [comment]
Changing to 2.4.0, since https://github.com/xunit/xunit/issues/1611 will be released no sooner than xunit 2.4.0. See https://github.com/xunit/xunit.analyzers/pull/92#pullrequestreview-98815686

**Comment by adamralph** [comment]
Changing back to 2.3.1, since https://github.com/xunit/xunit/issues/1611 is only in the analyzers package, and we may have a new release of that before xunit 2.4.0.
